package com.nextrade.domain.order;
import com.nextrade.common.enumtype.*; import com.nextrade.common.event.*; import com.nextrade.common.exception.*; import com.nextrade.common.identifier.*; import com.nextrade.common.util.*; import com.nextrade.common.valueobject.*; import com.nextrade.domain.instrument.Instrument; import com.nextrade.domain.shared.*; import com.nextrade.domain.user.User; import java.math.*; import java.time.*; import java.util.*;
public final class Order extends AbstractAggregateRoot<OrderId> {
 private final User user; private final Instrument instrument; private final OrderSide side; private OrderType type; private OrderStatus status; private TimeInForce tif; private final Quantity originalQuantity; private Quantity workingQuantity; private Quantity filledQuantity; private Price limitPrice; private Price stopPrice; private Price avgFillPrice; private final String clientOrderId; private Instant expiresAt; private Instant triggeredAt; private long sequence;
 private Order(User user,Instrument instrument,OrderSide side,OrderType type,Quantity quantity,Price limitPrice,Price stopPrice,TimeInForce tif,String clientOrderId){super(OrderId.generate());if(!instrument.tradeable())throw new InvalidOrderException("Instrument is not tradeable");this.user=Objects.requireNonNull(user);this.instrument=Objects.requireNonNull(instrument);this.side=Objects.requireNonNull(side);this.type=Objects.requireNonNull(type);this.originalQuantity=Objects.requireNonNull(quantity); this.workingQuantity=quantity;if(quantity.isZero())throw new InvalidOrderException("Quantity must be positive");this.limitPrice=limitPrice;this.stopPrice=stopPrice;this.tif=Objects.requireNonNull(tif);this.clientOrderId=clientOrderId;this.status=OrderStatus.NEW;this.filledQuantity=Quantity.zero();if(type.requiresLimitPrice()&&limitPrice==null)throw new InvalidOrderException("Limit price required");if(type.requiresStopPrice()&&stopPrice==null)throw new InvalidOrderException("Stop price required");}
 public static Order market(User u,Instrument i,OrderSide s,Quantity q,TimeInForce tif,String client){return new Order(u,i,s,OrderType.MARKET,q,null,null,tif,client);} public static Order limit(User u,Instrument i,OrderSide s,Quantity q,Price p,TimeInForce tif,String client){return new Order(u,i,s,OrderType.LIMIT,q,p,null,tif,client);} public static Order stopLoss(User u,Instrument i,OrderSide s,Quantity q,Price stop,TimeInForce tif,String client){return new Order(u,i,s,OrderType.STOP_LOSS,q,null,stop,tif,client);} public static Order stopLimit(User u,Instrument i,OrderSide s,Quantity q,Price p,Price stop,TimeInForce tif,String client){return new Order(u,i,s,OrderType.STOP_LIMIT,q,p,stop,tif,client);}
 public Quantity remaining(){return workingQuantity.subtract(filledQuantity);} public boolean active(){return status.isActive();} public boolean marketableAgainst(Price p){return switch(type){case MARKET->true;case LIMIT->side==OrderSide.BUY?p.compareTo(limitPrice)<=0:p.compareTo(limitPrice)>=0;case STOP_LOSS,STOP_LIMIT->throw new IllegalStateException("Stop order must trigger before matching");};}
 public boolean stopTriggered(Price last){if(last==null||!type.isStop())return false;return side==OrderSide.BUY?last.compareTo(stopPrice)>=0:last.compareTo(stopPrice)<=0;}
 public void trigger(Instant now){if(!type.isStop())return;if(status.isTerminal())throw new IllegalStateException("Terminal order");this.type=type==OrderType.STOP_LOSS?OrderType.MARKET:OrderType.LIMIT;triggeredAt=now;emit(new OrderTriggeredEvent(EventId.generate(),now,id().asString(),"Stop triggered at "+stopPrice));touch();}
 public void assignSequence(long seq){sequence=seq;} public long sequence(){return sequence;}
 public void fill(Quantity qty,Price price,TradeId tradeId){if(!active())throw new IllegalStateException("Inactive order");if(qty.isZero()||qty.compareTo(remaining())>0)throw new IllegalArgumentException("Invalid fill quantity");BigDecimal oldValue=avgFillPrice==null?BigDecimal.ZERO:avgFillPrice.value().multiply(filledQuantity.value());BigDecimal total=filledQuantity.value().add(qty.value());avgFillPrice=new Price(oldValue.add(price.value().multiply(qty.value())).divide(total,8,RoundingMode.HALF_EVEN),price.tickSize());filledQuantity=filledQuantity.add(qty);status=filledQuantity.compareTo(originalQuantity)>=0?OrderStatus.FILLED:OrderStatus.PARTIALLY_FILLED;emit(new TradeExecutedEvent(EventId.generate(),Instant.now(),tradeId.asString(),"Order fill "+id()));touch();}
 public void cancel(String reason){if(status.isTerminal())return;status=OrderStatus.CANCELLED;emit(new OrderCancelledEvent(EventId.generate(),Instant.now(),id().asString(),reason));touch();} public void reject(String reason){if(status.isTerminal())return;status=OrderStatus.REJECTED;emit(new OrderRejectedEvent(EventId.generate(),Instant.now(),id().asString(),reason));touch();} public void expire(){if(status.isTerminal())return;status=OrderStatus.EXPIRED;emit(new OrderExpiredEvent(EventId.generate(),Instant.now(),id().asString(),"TIF expired"));touch();}
 public void modify(Quantity newTotal,Price newLimit){if(!active())throw new IllegalStateException("Inactive order");if(newTotal==null||newTotal.compareTo(filledQuantity)<0)throw new InvalidOrderException("Quantity below filled amount");if(newTotal.compareTo(workingQuantity)>0)throw new InvalidOrderException("Quantity cannot increase");if(type==OrderType.LIMIT&&newLimit==null)throw new InvalidOrderException("Limit price required");this.limitPrice=newLimit;this.workingQuantity=newTotal;this.status=filledQuantity.compareTo(newTotal)>=0?OrderStatus.FILLED:status; // size reduction only; originalQuantity is immutable for audit
 touch(); }
 public User user(){return user;} public Instrument instrument(){return instrument;} public OrderSide side(){return side;} public OrderType type(){return type;} public OrderStatus status(){return status;} public TimeInForce tif(){return tif;} public Quantity originalQuantity(){return originalQuantity;} public Quantity workingQuantity(){return workingQuantity;} public Quantity filledQuantity(){return filledQuantity;} public Price limitPrice(){return limitPrice;} public Price stopPrice(){return stopPrice;} public Price avgFillPrice(){return avgFillPrice;} public String clientOrderId(){return clientOrderId;} public Instant expiresAt(){return expiresAt;} public Instant triggeredAt(){return triggeredAt;} public void expiresAt(Instant value){expiresAt=value;touch();}
}
