create table if not exists app_user(id uuid primary key,username varchar(50) not null unique,email varchar(255) not null unique,password_hash varchar(255) not null,role varchar(30) not null,status varchar(30) not null,email_verified boolean not null default false,failed_attempts int not null default 0,locked_until timestamptz,version bigint not null default 0);
create table if not exists wallet(id uuid primary key,user_id uuid not null references app_user(id),currency char(3) not null,available numeric(19,4) not null default 0,reserved numeric(19,4) not null default 0,version bigint not null default 0,unique(user_id,currency));
create table if not exists orders(id uuid primary key,user_id uuid not null references app_user(id),instrument_id uuid not null,side varchar(10) not null,type varchar(20) not null,status varchar(20) not null,tif varchar(10) not null,quantity numeric(19,4) not null,filled_quantity numeric(19,4) not null,limit_price numeric(19,4),stop_price numeric(19,4),avg_fill_price numeric(19,4),client_order_id varchar(128),expires_at timestamptz,triggered_at timestamptz,sequence bigint not null,version bigint not null default 0);
create unique index if not exists ux_orders_client on orders(user_id,client_order_id) where client_order_id is not null;
create table if not exists trade_event(id uuid primary key,buy_order_id uuid not null,sell_order_id uuid not null,buyer_id uuid not null,seller_id uuid not null,instrument_id uuid not null,quantity numeric(19,4) not null,price numeric(19,4) not null,sequence bigint not null,executed_at timestamptz not null);
create table if not exists user_session(id uuid primary key,user_id uuid not null references app_user(id),refresh_digest varchar(128) not null unique,status varchar(20) not null,expires_at timestamptz not null,created_at timestamptz not null,rotated_to uuid,version bigint not null default 0);
create table if not exists password_reset_token(id uuid primary key,user_id uuid not null references app_user(id),token_digest varchar(128) not null unique,expires_at timestamptz not null,used boolean not null default false,used_at timestamptz,version bigint not null default 0);
create table if not exists email_verification_entity(id uuid primary key,user_id uuid not null references app_user(id),selector varchar(128) not null unique,code_digest varchar(128) not null,expires_at timestamptz not null,attempts int not null default 0,max_attempts int not null default 5,used boolean not null default false,used_at timestamptz,version bigint not null default 0);
create table if not exists outbox_entity(id uuid primary key,aggregate_type varchar(100) not null,aggregate_id varchar(100) not null,event_type varchar(100) not null,payload text not null,status varchar(20) not null,available_at timestamptz not null,claimed_at timestamptz,claimed_by varchar(100),attempts int not null default 0,version bigint not null default 0);
